//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiningForShoppingBasket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discounts
    {
        public int Id { get; set; }
        public string DiscountName { get; set; }
        public string DiscountDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal DiscountCost { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
