//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiningForShoppingBasket
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReceipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleReceipts()
        {
            this.SaleRows = new HashSet<SaleRows>();
        }
    
        public int Id { get; set; }
        public System.DateTime SaleDateTime { get; set; }
        public int CashierId { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleRows> SaleRows { get; set; }
    }
}
