//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiningForShoppingBasket
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleRows
    {
        public int Id { get; set; }
        public int SaleId { get; set; }
        public int ProductId { get; set; }
        public decimal SaleQuantity { get; set; }
        public decimal TotalCost { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual SaleReceipts SaleReceipts { get; set; }
    }
}
