//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiningForShopingBasket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> GenderId { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual Genders Genders { get; set; }
    }
}
