//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMiningForShopingBasket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int id { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductTypeid { get; set; }
        public Nullable<double> Cost { get; set; }
    }
}
